#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    // three variables of type integer are instantiated, number is where the random number is saved in, try is where number of tries the user takes to guess the number is saved in, guess is the user's input of the number they guessed is saved in
    int number,guess;
    int try = 0;
    // variable 'game' that track's how many games are played and is intialised to 0
    int game = 0;
    // maximum number of games that can be played are 5000, ofcourse no one would play 5000 games this number is more of making it appear as an infinite game
    int scoreboard[5000];
    // again is intialised to y which means yes so that the first loop goes
    char again = 'y';
    // this is done to ensure that a different number is given to the variable number each time the code is run
    srand(time(NULL));
    // the loop goes if the user wants to play again and for the first time 'again' is already set to y
    while (again == 'y') {
        // number of tries for each game starts at 0
        try = 0;
        // creating a new random number each game
        number = (rand() % 5000) + 1;
        printf ("Whenever you want to exit the game enter 0\n");
        // while (1) is an infinit loop
        while (1) {
            printf ("Guess this random number between 1 and 5000: ");
            // the user's guess is saved on to variable guess
            scanf ("%d", &guess);
            if (guess == 0) {
                printf ("Game exited\n");
                // if the user exited the game the number stored in the scoreboard array of this game would be 0 and +1 is added to the game variable and the loop is exited through break
                scoreboard[game] = 0;
                game++;
                break;
            }
            // +1 is added to the try variable after each guess the user takes
            try++;

            if (guess == number){
                printf ("thats correct you got it on the %dth try\n", try);
                // if the user guessed correctly the number of tries is stored in the array scoreboard for this game and then +1 is added to game array to start tracking the next game and the loop is exited through break
                scoreboard[game] = try;
                game++;
                break;
            // the user here is getting help by printing guess higher and guess lower based on the user's guess compared with the random number
            } else if (guess < number)
                printf ("Guess higher\n");
            else
                printf ("Guess lower\n");
        }
        // the user is asked to play again and the response is saved in the variable again if the response was 'y' for yes then the loop runs again if not 'n' for no then the scoreboard is printed
        printf("Do you want to play again (y/n): ");
        scanf(" %c", &again);

    }

    printf ("scoreboard:\n");
    // looping through all the games played by the user
    for (int i = 0; i < game; i++){
        // if there was any zeros saved in the array 'scoreboard' then it would display to the user that the game was ended if not the user can see how tries he/she took to win the game
        if (scoreboard[i] == 0)
            printf("Game %d: Game Was Ended\n", i + 1);
        else
            printf("Game %d: %d tries\n", i + 1, scoreboard[i]);
    }












    // printf ("%d", number);
    // for loop that goes until 5000, its main purpose is to count how many tries it takes the user to guess the random number
    // while (again == 'y') {
    //     // 
    //     try = 1;
    //     // a random number is generated and it is capped at 5000 which means any number between 0 and 4999 so 1 is added to the final number which makes it a random number between 1 and 5000
    //     number = (rand() % 5) + 1;
    //     // telling the user to input a number
    //     printf ("Guess this random number between 1 and 5000: ");
    //     // saving the number inputed by the user in to variable guess
    //     scanf ("%d", &guess);
    //     // 
    //     try++;
    //     // if statment that compares the users guess with the random number generated by the code
    //     if (guess == number) {
    //         // if the numbers are equal then the user gets promted with a message saying thats the correct number and telling the user on which try they guessed corect
    //         printf ("thats correct you got it on the %dth try\n", try);
    //         // 
    //         printf ("Do you want to play again (y/n): ");
    //         // 
    //         scanf ("%s", &again);
    //         // 
    //         if (again == 'y'){
    //             scoreboard[game] = try;
    //             game++;
    //         } else if (again == 'n') {
    //             for (int i = 0; i < game; i++){
    //                 printf ("you won game %d on the %dth try", i+1, scoreboard[i]);
    //             }
    //         }
    //     // to make the game a bit easier the code is comparing the users's guess with the random number
    //     } else if (guess < number){
    //         // if the the user's guess is less than the random number then the user get's promted with the message below
    //         printf ("Guess higher\n");
    //     } else {
    //         // if the the user's guess is higher than the random number then the user get's promted with the message below
    //         printf ("Guess lower\n");
    //     }
    // }
    
    // for (try = 1; try <= 5000; try++) {
    //     // 
    //     number = (rand() % 5) + 1;
    //     // telling the user to input a number
    //     printf ("Guess this random number between 1 and 5000: ");
    //     // saving the number inputed by the user in to variable guess
    //     scanf ("%d", &guess);
    //     // if statment that compares the users guess with the random number generated by the code
    //     if (guess == number) {
    //         // if the numbers are equal then the user gets promted with a message saying thats the correct number and telling the user on which try they guessed corect
    //         printf ("thats correct you got it on the %dth try", try);
    //         // 
    //         scoreboard[game] = try;
    //         game++;
    //         break;
    //         // 
    //     // to make the game a bit easier the code is comparing the users's guess with the random number
    //     } else if (guess < number)
    //         // if the the user's guess is less than the random number then the user get's promted with the message below
    //         printf ("Guess higher\n");
    //     else
    //         // if the the user's guess is higher than the random number then the user get's promted with the message below
    //         printf ("Guess lower\n");
    // }
    // printf ("Do you want to play again (y/n): ");
    //     // 
    //     scanf ("%s", &again);
    //     // 
    //     if (again != 'y'){
    //         for (int i = 0; i < game; i++){
    //             printf ("you won game %d on the %dth try", i+1, scoreboard[i]);
    //         }
    //     }
}